### ISSUE TITLE
Can I set a debug launch config?

### ISSUE THREAD

**Issue by JonathanMEdwards** [kavod-io/vscode-jest-test-adapter#125]
I want to set skipFiles for debugging exceptions in tests. Can I specify a launch config for debugging tests?

**Comment by marknorrapscm** [comment]
I agree that this is needed, specifically for the purpose you mentioned of being able to set `skipFiles` so that we can avoid ending up in `async_hooks.js` every time we try to step into an async function.

Right now, clicking the "Debug" button seems to generate and run the Jest CLI command for us. Something like this:

```
C:\Code\MyProject/node_modules/.bin/jest.cmd --runInBand --testPathPattern c:\\Code\\MyProject\\src\\my-function\.test\.js --testNamePattern ^My Test Name$
```

There is no way, that I can see, for a `vscode/launch.json` or any other config file to be taken into consideration.
