### ISSUE TITLE
Please provide a way to restart the service

### ISSUE THREAD

**Issue by jethas-bennettjones** [kavod-io/vscode-jest-test-adapter#128]
There are instances when a test will cause the Jest process to run indefinitely, such as when a promise is left incomplete, especially in async test, and currently the only way to resolve this issue is to restart VSCode, which seems a bit extreme.
It would be great if there were a way to kill and restart the test processes from the Command Palette rather than needing to restart VSCode itself.

**Comment by RA80533** [comment]
This is a good idea. Although it certainly is not the responsibility of the test runner to ensure that all tests are closed, this is likely a common occurrence for those testing asynchronous code.

@jethas-bennettjones, for the time being, try restarting the extension host instead of restarting VS Code entirely. This can be done through the **Developer: Restart Extension Host** command.

The command might leave a Node.js process hanging somewhere but I'm not sure. You you would be able to check if that's the case by running `ps -x | grep "node"` and killing whichever processes you believe might be hanging. Use discretion if you decide to do so.
