### ISSUE TITLE
Nwrl Nx Support

### ISSUE THREAD

**Issue by wSedlacek** [kavod-io/vscode-jest-test-adapter#14]
First off, thank you so much for picking up this project. I tested the latest branch today and it fixes many of the issues I had with the previous versions of this project. Your work is definitely awesome.

Secondly I would like to make a feature request, it seems like you have a road map planned and you are making commits very often which is awesome however I would like to request that support be added for Nwrl Nx a mono repo solution.

The current extension does load up in a Nwrl Project but runs into problems because it is running directly from the jest binary. I purpose detecting is an angular project (with `angular.json` in the root) and if it is default to running jest with `ng test` instead of the jest binary. This will run jest through `@angular-builders/jest` and use the settings in `angular.json`.

Adding this support would be super awesome and make this extension super usable in my daily workflow. Nx defaults to using jest so having support for this would be a match made in heaven imho.

**Comment by rossknudsen** [comment]
Hey @wSedlacek. Thanks for the compliment. It did seem the original project was dead (I did try to raise a PR there).

Interestingly I'm working on a Nx.dev project at work currently although it is React not angular.  It is part of the reason I created #9.  Although your use case does appear to supplement it.

if you're interested in raising a PR that'd be great. I'm keen to involve others in this too.

**Comment by wSedlacek** [comment]
I would love to help out if I find the time! I will definitely make pull request towards this if I find the opportunity.

**Comment by rossknudsen** [comment]
I've done a bit of investigation into this one.  In our React project the nx.json and workspace.json files just reference the jest.config.js files in each app/lib.  So I tried changing cwd to one of the apps and running jest from there (I had to provide a reference back to the jest binary).  The tests all ran fine.  It would be great if you could confirm that it works for you too.

If this is the case, I think we could handle monorepos by accepting a function that provides all the app/lib roots. That way it might work for other monorepos.

**Comment by wSedlacek** [comment]
It won't be that simple with Angular I am afraid.
When using NX with Angular it hooks into the Angular CLI.
In order for test to run properly from Angular they need to be triggered via the Angular CLI binary `ng` as the Angular CLI must first check `angular.json` to read the test settings (example bellow)
Starting from just the `jest` binary will yield nothing but errors starting with one that says Zone.js isn't initialized.

```
{
  "projects": {
    "project-name": {
      "architect": {
        "test": {
          "builder": "@nrwl/jest:jest",
          "options": {
            "jestConfig": "apps/project-name/jest.config.js",
            "tsConfig": "apps/project-name/tsconfig.spec.json",
            "setupFile": "apps/project-name/src/test-setup.ts"
          }
        }
      }
    }
  }
}
```

It is that `@nrwl/jest:jest` builder that then calls the jest binary. So your best bet to get it working with Angular and Nx for Angular is likely gonna be to offer a setting for Angular then if it is set attempt to use the `ng` binary, if it doesn't exist throw a notification that it doesn't appear to be installed.

Resource:
- https://blog.nrwl.io/nrwl-nx-6-3-faster-testing-with-jest-20a8ddb5064
- https://github.com/thymikee/jest-preset-angular

**Comment by rossknudsen** [comment]
Thanks for the feedback.  I'm sure that it will be possible somehow.  I ran across [this documentation](https://wallabyjs.com/docs/integration/nrwl.html) which explains why you can't just run jest directly in the app directory and have the tests run.  I added the suggested config and the tests work from either the repo root or the app root.  Resulting config:

```js
module.exports = {
  name: 'angular-test-workspace',
  preset: '../../jest.config.js',
  coverageDirectory: '../../coverage/apps/angular-test-workspace',
  snapshotSerializers: [
    'jest-preset-angular/AngularSnapshotSerializer.js',
    'jest-preset-angular/HTMLCommentSerializer.js'
  ],
  setupTestFrameworkScriptFile: '<rootDir>/src/test-setup.ts',
  globals: {
    'ts-jest': {
      tsConfig: "<rootDir>/tsconfig.spec.json",
      diagnostics: { warnOnly: true },
      stringifyContentPathRegex: "\\.html$",
      astTransformers: ["jest-preset-angular/InlineHtmlStripStylesTransformer"]
    }
  }
};
```

From repo root command (use `projects` flag to indicate where the projects are located):
`node_modules\.bin\jest --projects apps\angular-test-workspace\jest.config.js`

From app root (note no extra config):
`..\..\node_modules\.bin\jest`

You might be wondering why I'm pursuing this so hard.  The reason is that this extension relies heavily on `jest-editor-support` which actually runs Jest.  I'm hoping that I don't need to have any custom code to run library specific stuff if possible.

The other thing I found is that `ng test` will accept the `--json` flag which `jest-editor-support` uses to get the test output as json which it can process.  However there does still seem to be some other test run text emitted as well.  So I'd need to see how `jest-editor-support` suppresses that and see if that/those flags can be used as well.

**Comment by rossknudsen** [comment]
Also I just managed to figure out how to pass all the extra config through the command line too (note all the escaping in Windows):

`..\..\node_modules\.bin\jest --setupFilesAfterEnv apps\angular-test-workspace\src\test-setup.ts --globals "{""ts-jest"": {""tsConfig"": ""<rootDir>/tsconfig.spec.json"",""diagnostics"": { ""warnOnly"": true },""stringifyContentPathRegex"": ""\\.html$"",""astTransformers"": [""jest-preset-angular/InlineHtmlStripStylesTransformer""]}}"`

**Comment by wSedlacek** [comment]
Wow. You have found out so much in just a few hours. I honestly didn't hear of Wallaby before now. It's implementation does show this is possible, it's a shame their code seems to be proprietary.

I do have one other concern about bypassing the Angular/Nx CLI that you likely have considered but I would like it to be on this issue for documentation. That is that I would prefer that the solution to this problem not be reliant on an implementation detail of either the Nx or Angular CLI. By that I mean that the internal code of both of these CLIs and how they call Jest are likely to change in the future and bypassing them to call the Jest Binary directly may yield future comparability issues. If we could get the Angular CLI or Nx CLI to behave as the Jest Binary for the use of jest-editor-support then I believe that will yield the most maintainable results as the interface for the CLIs themselves is much likely to change then how they are internally calling the Jest binary. For example in the future Angular may drop Zone or something.

Getting the Angular or Nx CLI to work would also mean that users can take full advantage of the angular.json for example swapping out environment variables for testing similar to how they do for production. 

It seems like you may be on to something with that `--json` flag. If the problem is a that the Angular CLI doesn't support the right arguments or produce the right output to behave as a Jest Binary target then we may look into if those arguments are passed directly to the builders maybe we could implement a Angular CLI builder that wraps the Nx builder to intercept the required command line arguments and parses the outputs into what the jest-editor-support needs?

Granted that would be one additional project to maintain which may not be ideal, but if it is simply an interface issue then it may only need to be something super simple to wrap the builder and not need that much maintenance.

References
- https://angular.io/guide/cli-builder
- https://medium.com/angular-in-depth/angular-cli-builder-26f0981fb7f3
- https://blog.angular.io/introducing-cli-builders-d012d4489f1b
- https://medium.com/dailyjs/angular-cli-6-under-the-hood-builders-demystified-f0690ebcf01

**Comment by rossknudsen** [comment]
What about if there was a configuration file such as `vscode-jest-test-adapter.config.js` similar to `jest.config.js` and `prettier.config.js` etc?  I was thinking something along the lines of this definition:

```ts
// use cosmiconfig or similar.
// vscode-jest-test-adapter.config.js
export interface VscodeJestTestAdapterConfig {
    /**
     * Either full instances of JestTestProject or strings containing paths to the projects.
     * 
     * Ideally the default implementation for finding projects should handle Lerna/Nx/Yarn Workspaces.
     * Only override when wanting custom handling.
     */
    projects?: (JestTestProject | string)[];

    /**
     * Partial Jest configuration objects that will be merged with the default Jest configuration options.
     * 
     * Ideally the default implementation for finding projects should handle Lerna/Nx/Yarn Workspaces.
     * Only override when wanting custom handling.
     */
    jestConfig?: any;  // TODO type as Partial<JestConfig>
}

interface JestTestProject {
    /**
     * The path to the jest project, usually jest.config.js or possibly a directory containing this file.
     */
    path: string;
    /**
     * The optional display name of the project.  Will default to the leaf directory node of the path value.
     * 
     * E.g. path: '/home/user/src/apps/my-project/jest.config.js' will yield default value of name: 'my-project'
     */
    name?: string;
}
```

The idea being that the default implementation ideally will handle the major monorepo implementations but if you really wanted to, you could write a JS config file to provide the project paths and Jest config overrides dynamically.  A custom implementation could then read any of the Nx config files or other environment variables and produce a dynamic response.  

Alternatively or as well as - there could be an option for a custom runner, which could be a wrapper for the underlying `nx`/`ng` command line.  I'm not sure what kind of interface that would look like.  But you're welcome to spec something up.

I think the extension will need to have code that works out whether it is running in a monorepo and if so which kind and then handles the default/common setups out of the box.  Then allow for sufficient customization so that people don't have to wait for a feature to be implemented to get their particular project to run.  I haven't done anything like the above before, so I'm open to ideas.

**Comment by wSedlacek** [comment]
Having a config file is an interesting idea. The naming though I think could use some work.

If it starts with `vscode` then that indicates that is should actually be going in the .vscode folder rather then having that as part of the file name.

**Comment by wSedlacek** [comment]
WOW! You certainly have made quite a bit of progress.
I was attempting to review the latest commit on the `monorepo` branch and it looks really good!
One bug I did encounter when testing it was this.
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
```

Coming from here:
https://github.com/kavod-io/vscode-jest-test-adapter/blob/adfca75bdc4562be0260747300a58895ee03f33e/src/repo/NxdevAngular.ts#L54

The problem is that `setupFile` is an optional param so on the libraries I have that do not use it this error gets thrown.

I also was noticing that it was not passing the options like `passWithNoTests` into the extension.
The full schema for the Jest Builder is here for reference:
https://github.com/nrwl/nx/blob/master/packages/jest/src/builders/jest/schema.json

**Comment by wSedlacek** [comment]
I started to play around with Web Storm and I was able to get my NX Nwrl repo to work with their Jest testing run directly through the CLI by:

1) Adding the following config settings to every Angular app and library's jest.config.js
```js
  globals: {
    'ts-jest': {
      stringifyContentPathRegex: '\\.html$',
      tsConfig: '<rootDir>/tsconfig.spec.json',
      astTransformers: [
        'jest-preset-angular/build/InlineFilesTransformer',
        'jest-preset-angular/build/StripStylesTransformer',
      ],
    },
  },
  setupFilesAfterEnv: ['<rootDir>/src/test-setup.ts'],
```

2) Adding the following line to the root jest.config.js
```js
  projects: ['<rootDir>/apps/*/jest.config.js', '<rootDir>/libs/**/jest.config.js'],
```

**Comment by rossknudsen** [comment]
> WOW! You certainly have made quite a bit of progress.

Cheers.  I was on holiday and working on this kind of thing is what I like to do in the evenings.

> The problem is that `setupFile` is an optional param so on the libraries I have that do not use it this error gets thrown.

Nice detective work!  I came to the same conclusion the other day when I tested the extension with our Nx React repo, which doesn't have any setup files.  I'm in two minds as to whether to even bother tracking it.  I guess I'll check what the Nx test code is doing and decide.

> I also was noticing that it was not passing the options like `passWithNoTests` into the extension.

Hmmm, I did see that at one point as well, I'll have to have a look at that.

**Comment by rossknudsen** [comment]
> I started to play around with Web Storm and I was able to get my NX Nwrl repo to work with their Jest testing run directly through the CLI by:
> ...

Perfect, that's exactly what you need to do and I appreciate the testing on your behalf.  TBH I was going to reply and see if you would do that favour.

Obviously, I wouldn't expect anyone to modify their configuration files like that in the long term (I don't know if it will break the Nx dev functionality).  At the moment, for running the tests I'm using the `jest-editor-support` package, which runs jest on the command line and parses the output.  I think in the long term, this isn't the best option.  In the case of Nx.dev, it would mean either modifying the config files on disk and then reverting them (yuck), or creating temp config files somewhere with the required modifications (less yuck).  But I'm considering whether I take a different approach and actually add Jest to my extension and use the `jest.runCLI` command, which is what the Nx Angular test script does.  This would reduce version conflicts in Jest (i.e. if jest config options change over time) and I don't think there should be any changes in Jest itself that should change whether user's unit tests pass or not.  It would mean that I can pass a Jest config object instead of the path to a config file, which would allow me to modify the config as required by packages like Nx Angular.

But my plan is to tidy up a couple of issues, like you've discovered and try getting the test debugging working correctly and then I'll probably publish to the extension store.  It'll be a prerelease, since I don't have unit tests in place - but it'll mean that I can start getting some user feedback and issues from a wider audience.

**Comment by SSmale** [comment]
Is there any update on how to get this working with nx angular? Thanks for the awesome work!

**Comment by wSedlacek** [comment]
@SSmale My message from 28 days ago details the config changes I used to get this working.
Basically rather then treating each projects `jest.config.js` as a super set for the workspace's root you instead treat them as individuals that are imported to the root as `projects`. This configuration also works for running NX projects with Wallaby

Here is my WIP project where I have this implemented and working
https://gitlab.com/wsedlacek/ccg-x/-/tree/cards-api

It may be nice to edit the schematics to generate projects in this way to avoid having to set it up like this on every project/library generation.

![Screen Shot 2020-04-09 at 16 36 01](https://user-images.githubusercontent.com/8206108/78942885-3ca3ed00-7a80-11ea-89c0-4683d701d016.png)

**Comment by SSmale** [comment]
Thanks for the quick reply @wsedlacek, I’ll give that a go but I was referencing the other work being done on not having to edit configs.

**Comment by rossknudsen** [comment]
I discovered that the jest-editor-support library can accept a command other than a path to the Jest executable.  I've just pushed support for Create React App which was in the same boat as this.  So I may be able to implement this support without major changes.  Hopefully, you'll see it soon.

**Comment by rossknudsen** [comment]
Just an FYI - I've found that Nx will need a PR to allow for the retrieval of settings using the `nx test` command.  Using plain Jest it would be something like:
```
npx jest --showConfig
```
But Nx doesn't pass through the `showConfig` flag.  They also may not accept the PR - but it seems harmless to me.

**Comment by rossknudsen** [comment]
Good news, the changes were accepted into Nx.  Just need to wait for the next release.  Not sure what the release cancer is, but if you see it before I do, feel free to comment.

**Comment by rossknudsen** [comment]
I added this support behind a dev toggle (**UseNxCli**) so you can test this feature the old way as well as the new way.  But you'll still have to wait for the next Nx Dev release >9.2.4.

**Comment by wSedlacek** [comment]
Awesome work @rossknudsen! Can't wait to try it out!
