### ISSUE TITLE
Error loading tests

### ISSUE THREAD

**Issue by nero120** [kavod-io/vscode-jest-test-adapter#25]
I must be doing something really dumb as I can't even get it to load my tests, the diagnostic logs aren't particularly helpful:

```
[2020-04-14 21:36:12.426] [INFO] Loading Jest tests...
[2020-04-14 21:36:12.428] [ERROR] Error loading tests {}
[2020-04-14 21:36:12.429] [INFO] Finished loading Jest tests.
```

I'm using ts-jest and my jest config is in a json file `/jestconfig.json`. I've played with the jest test adapter settings but whatever I do it just outputs the above log.

Any ideas?

**Comment by rossknudsen** [comment]
Hey @nero120,

The second log line is supposed to serialize the error object out, but looks like I didn't test that thoroughly.

Also, it looks like I am only searching for `jest.config.js` currently, so that will be causing the error.  You could try (as a diagnostic) changing the config to the previously mentioned format and see if it loads if you want.

- [ ] Update error logging statements to serialize error object correctly.
- [ ] Update Jest configuration filename identification to include all possible formats.

**Comment by pbotsman** [comment]
Hi!

First of all, thank you for adopting this extension! I was missing it. 😄 

I am also having a problem loading tests.
I had my jest config inside `package.json` under `jest` key, but then I created a separate file `jest.config.js`.

What I noticed:
1. setting `jestTestExplorer.pathToJestConfig` does not seem to work (probably you are aware of this, but I mention it just in case)
2. if I put `jest.config.js` in the root directory of my project, I am getting an error: 
"[2020-04-15 06:16:08.044] [ERROR] Error while reloading all tests. [SyntaxError: Unexpected character '[2020-04-15 06:16:08.045]"

It looks like such an error is caused by the line `testRegex: "./tests/js/.*\\.(test|spec)\\.jsx?$"` in my `jest.config.js`.

Here is the content of the `jest.config.js`:
```
module.exports = {
  testRegex: "./tests/js/.*\\.(test|spec)\\.jsx?$"
}
```

If necessary, I am ready to provide any additional information or do some testing.

**Comment by nero120** [comment]
@rossknudsen thanks for the quick response! Yes changing the config file to `jest.config.js` and `module.exports` format sorted it, so I'll close the issue.

**Comment by rossknudsen** [comment]
Thanks heaps for confirming that "fixed" the problem.  I don't think that asking people to change their choice of config is an acceptable solution - so I'll still work on making it work with all valid Jest configurations.  I don't think that it will be a huge amount of effort `cosmiconfig` does a lot of the heavy lifting.

**Comment by rossknudsen** [comment]
@pbotsman
> 1. setting `jestTestExplorer.pathToJestConfig` does not seem to work (probably you are aware of this, but I mention it just in case)

I think that is a hangover from the previous implementation.  Ideally, you shouldn't need to set this, once I make the necessary changes.  So I'll look to remove that setting too.

> 2. if I put `jest.config.js` in the root directory of my project, I am getting an error:
>    "[2020-04-15 06:16:08.044] [ERROR] Error while reloading all tests. [SyntaxError: Unexpected character '[2020-04-15 06:16:08.045]"

Its a bit disappointing that its not clear what the syntax error is.  Looks like I need to update more of the logging statements.

> ```
> module.exports = {
>   testRegex: "./tests/js/.*\\.(test|spec)\\.jsx?$"
> }
> ```

Just looking at your regex.  It looks fine except for the leading dot.  Is that correct?  It would match any single character.

I'm presuming that if you remove the jest key from package.json and run Jest from the command line, that it works fine with the above config file?  If so, then try altering the regex expression to target a single test file, or remove/rename all but one test file to see if there is an issue with a particular test file.  Basically try that approach to isolate where the problem is.  If a single file still fails, try targeting a single test file with a simple test in it that should always run.

**Comment by pbotsman** [comment]
@rossknudsen thank you for the fast reply and trying to help me!

1. okay, good!
2. It turn out the problem is related to my particular project. I've tried using exactly the same config for a different project and it worked fine.
I don't know what is the reason behind that error though, but I think I can find a workaround anyway.

Thanks!

**Comment by rossknudsen** [comment]
The other thing that comes to mind is whether any of your test files have a BOM in them.  https://en.wikipedia.org/wiki/Byte_order_mark

**Comment by pbotsman** [comment]
I don't have such a character in my tests or any other files.
I think that for now we can forget about it, it's not a critical issue for me.
If I find out what cases this error, I will open a new issue.

Thanks again for your help!

**Comment by rossknudsen** [comment]
@nero120 I'd be interested if the latest release works with the original config file name. I added support for more jest configs.

**Comment by nero120** [comment]
@rossknudsen in v0.3.1 and v0.3.2 the `Path To Jest Config` setting is missing, how does it know which jest config file to use?
`

**Comment by rossknudsen** [comment]
Hmmm. When I think about it, it still won't work for your old config file name, as it's not one of the "standard" ones I've implemented.

Also the extension setting for a config file path is the equivalent of the`--config` CLI option.  My issue is what to do when there are more than one config in a repo (multiple projects, monorepo etc).
