### ISSUE TITLE
Support Create React App Projects

### ISSUE THREAD

**Issue by blake-mealey** [kavod-io/vscode-jest-test-adapter#40]
Hey, thanks for working on this adapter!

I am trying to get it working on a new create-react-app project, and I see this error in the logs:

```
[2020-04-23 21:48:34.200] [INFO] Loading Jest tests...
[2020-04-23 21:48:34.206] [INFO] No RepoParser available for project: <path-to-my-project>
[2020-04-23 21:48:34.207] [INFO] Finished loading Jest tests.
```

Any ideas?

**Comment by rossknudsen** [comment]
I'll have to try a CRA app. Let me come back to you.

**Comment by rossknudsen** [comment]
Ok, just created one and I realized that it doesn't just run Jest on the command line, it runs `react-scripts test` instead.  There is no default `jest.config.js` or other similar config created out of the box.  If you wanted you could create a simple one for testing.

However, I will need a specific implementation for CRA by the looks.  I definitely want to support this use case - I particularly like CRA.

**Comment by rossknudsen** [comment]
FYI I added the following and it found the tests, although the config is not sufficient to make the tests run/pass.

```js
// jest.config.js
module.exports = {}
```

**Comment by blake-mealey** [comment]
Thanks for looking into this!

Yeah, it's using react-scripts, although I can also run them by calling jest directly in my terminal:

```sh
./node_modules/.bin./jest
```

seems to run the tests as expected.

**Comment by rossknudsen** [comment]
Yeah, this extension needs a physical Jest config to recognize the existence of a project.  This is a limitation that I need to address, because as you've rightly noted, you can run Jest using the defaults, i.e. with no explicit config.

What react-scripts does is dynamically creates a config and runs jest directly - rather than from the command line.  I logged out the config from my test CRA app.  The following is a workaround that seems to get the tests working for the default setup:

```js
// jest.config.js

module.exports = {
  "setupFiles": [
    "<rootDir>\\node_modules\\react-app-polyfill\\jsdom.js"
  ],
  "setupFilesAfterEnv": [
    "<rootDir>/src/setupTests.js"
  ],
  "testEnvironment": "jest-environment-jsdom-fourteen",
  "transform": {
    "^.+\\.(js|jsx|ts|tsx)$": "<rootDir>\\node_modules\\react-scripts\\config\\jest\\babelTransform.js",
    "^.+\\.css$": "<rootDir>\\node_modules\\react-scripts\\config\\jest\\cssTransform.js",
    "^(?!.*\\.(js|jsx|ts|tsx|css|json)$)": "<rootDir>\\node_modules\\react-scripts\\config\\jest\\fileTransform.js"
  },
  "transformIgnorePatterns": [
    "[/\\\\]node_modules[/\\\\].+\\.(js|jsx|ts|tsx)$",
    "^.+\\.module\\.(css|sass|scss)$"
  ],
  "moduleNameMapper": {
    "^react-native$": "react-native-web",
    "^.+\\.module\\.(css|sass|scss)$": "identity-obj-proxy"
  },
  "moduleFileExtensions": [
    "web.js",
    "js",
    "web.ts",
    "ts",
    "web.tsx",
    "tsx",
    "json",
    "web.jsx",
    "jsx",
    "node"
  ],
}
```

I'm leaving it here for those that might want to get this working before I make the needed changes to make it work out of the box.

**Comment by blake-mealey** [comment]
Cool, thanks for the workaround. Would you be able to give a rough timeline on how soon you think CRA will be supported?

**Comment by rossknudsen** [comment]
To support it properly, will need #41 to be completed - since this will handle identifying projects that do not have an explicit Jest configuration (ones that rely on the default Jest configuration).  I have been experimenting with that task currently and have been making some headway (I don't think I've pushed anything yet).  So with any open source project, its hard to say how long it will take, but it is the highest feature priority at the moment.  However, I am looking at #42 at the moment to see if I can fix up `jest-editor-support` to handle that case.
