### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by cyberbiont** [kavod-io/vscode-jest-test-adapter#54]
I get "Jest encountered an unexpected token" error when using ES6 import syntax in my tests.

I have "jest": "26.0.1",  @babel/core": "^7.9.6"  and  "@babel/preset-env: "^7.9.6" installed and the following configuration in my package.json: 
```json
"babel": {
		"presets": [
			[
				"@babel/preset-env",
				{
					"targets": {
						"node": "current"
					}
				}
			]
		]
	}
}
```
Placing that config in babel.config.cjs doesn't help either.

Running Jest from the command line with "jest -i" works and successfully executes the test.
Other extensions like "Jest runner" also work.

**Comment by rossknudsen** [comment]
Couple of questions:
If you comment out/remove the barrel config, do other test runners fail with the same error?
Is your codebase using a framework, e.g. Create React App?

**Comment by rossknudsen** [comment]
Also, if your codename is open source, I can debug it myself.

**Comment by cyberbiont** [comment]
Yes, it I remove Babel configuration, console command fails with the same error.
Here's the sample repository. Basically it's a template with one simple task.
https://github.com/cyberbiont/task-js--random

**Comment by rossknudsen** [comment]
Ok, I did a little triage and I can reproduce the issue on the command line.  If you do the following, you should be able to reproduce also (note, this is for Windows - you'll have to translate for other OSes):

```cmd
> cd node_modules/.bin
> .\jest.cmd --projects ..\..
```

I recently changed the extension to set the working directory to the `bin` folder so that I could just pass `jest.cmd` as the command - which overcame an issue with whitespace chars in the execution path.  

It seems that Jest finds the Babel config when executed from the project root directory - if you find where this behaviour is documented, that would be awesome too.  It might help me understand how it works in one folder and not another.
