### ISSUE TITLE
Test suite failed to run -> SyntaxError

### ISSUE THREAD

**Issue by deaquino** [kavod-io/vscode-jest-test-adapter#66]
When I launch a test from the extansion panel I get this error:
It looks like expects js not ts or something

  ● Test suite failed to run

    SyntaxError: ...\my.component.spec.ts: Unexpected token, expected ";" (10:15)

       8 | 
       9 | describe('Component: MyComponent', () => {
    > 10 |   let component: MyComponent;

I'm not sure why I'm facing this issue.
When I run the tests manually they work just fine.

**Comment by rossknudsen** [comment]
Cool, can you see if you have v0.5.1 installed (the latest) and let me know if the problem persists?

If it still exists, describe the structure of your project and where the jest config is in particular.

**Comment by rossknudsen** [comment]
FYI 0.6.0 is latest now.

**Comment by VynDesign** [comment]
I am getting this issue with v0.7.4. Previously used rtbenfield/vscode-jest-test-adapter version with no issue, but saw this updated version and just installed it and uninstalled the older version.

It's possible that the jest.config.js file is not being acknowledged, since the error indicates it has no knowledge of TypeScript syntax. That file is responsible for configuring the transform library (ts-jest) in our applications:

`module.exports = {
    "roots": [
        "<rootDir>"
    ],
    globals: {
        'ts-jest': {
            diagnostics: false
        }
    },
    "transform": {
        "^.+\\.tsx?$": "ts-jest"
    },
    "testRegex": "(/__tests__/.*|(\\.|/)(test|spec))\\.tsx?$",
    "moduleFileExtensions": [
        "ts",
        "tsx",
        "js",
        "jsx",
        "json",
        "node"
    ],
    "moduleNameMapper": {
        "\\.(css|html|hbs|yml|yaml|txt)$": "<rootDir>/test/__mocks__/static-resources-mock.ts"
    },
    "testEnvironment": 'node',
    "reporters": ["default", "jest-junit"]
}`

Also had to add this to package.json, as the tests from our /dist folder were showing up as well as our test from /src folder:

`    "testPathIgnorePatterns": ["<rootDir>/dist/"]`

Again, not something that was necessary with the older version of the plugin.

**Comment by Mossop** [comment]
I'm seeing this issue too, tests in typescript files just fail because they seemingly aren't being handled by ts-jest. Running jest from the command line works. Is there some way to see the command line that this extension is calling?

**Comment by Enubia** [comment]
i've taken a look into the codebase since this issue bothers me aswell and it seems like that it should be an easy fix. the 
<img width="505" alt="image" src="https://user-images.githubusercontent.com/44695100/121142010-dc533b80-c83b-11eb-8555-65b10a7801f0.png">
as you can see here the config path is simply not implemented so creating an option to specify the config shouldn't be too much of an issue i assume?
