### ISSUE TITLE
Decorations

### ISSUE THREAD

**Issue by cyberbiont** [kavod-io/vscode-jest-test-adapter#70]
Just wondering what happened to error decorations. It was a useful feature, I remember it was working and now it is not, was it deprecated for some reason?

**Comment by rossknudsen** [comment]
I haven't deprecated it. But it may have broken - possibly with the changes to the host extension.  Do you have a repro, just so I understand what you mean.

**Comment by rossknudsen** [comment]
![image](https://user-images.githubusercontent.com/2489915/84557310-12bbbf00-ad7e-11ea-9332-e47c141c76bc.png)

Note that I get the above with a very contrived example.

**Comment by cyberbiont** [comment]
OK, seems like I can provide some new information.
First of all, I noticed that decorations show up, but then disappear after saving the editor (is it by design?)

If there are several `it` / `test` blocks with the same name (each inside different `describe` block) decorations show up only near the first one:

![dec duplicate](https://user-images.githubusercontent.com/59398323/84605211-3f69f680-aea4-11ea-8229-af1314781fe4.PNG)

Also, if there is an error, output text is corrupted:

![error](https://user-images.githubusercontent.com/59398323/84605335-2d3c8800-aea5-11ea-8d06-c2af6bc6219b.png)

Here's a minimal repo for reproduction
https://github.com/cyberbiont/ts-jest-test

**Comment by rossknudsen** [comment]
Yes, when you save a file, it will invalidate any previous test run - because the test result could be invalid.

> decorations show up only near the first one

This could actually be a defect, I'll have to look into that one.

> Also, if there is an error, output text is corrupted:

Yes, I know about that one.  Those 'corrupt' characters are unicode characters that encode the colour that you would see in a terminal that supports it.  In VS Code this is only supported in a few places.  I need to fix those places up - I wish that they supported it in more places.

Thanks for the repro code as well 😄
